using UnityEngine;
using UnityEngine.SceneManagement;
using Photon.Pun;

/// <summary>
/// Plays the menu loop in the menu and the combat loop in a match, and crossfades between them.
///
/// Lives on RoomManager, which survives the trip between scenes - a music player that reloads
/// with the scene restarts the track every time you join a room, which is worse than no music.
/// Two sources rather than one so a change is a fade rather than a cut; everything else here
/// snaps on purpose, but music is the one thing where a hard cut sounds like a bug.
///
/// Does nothing at all if the clips aren't there. They're generated by tools/music_generator.py
/// and deleting them is the whole uninstall.
/// </summary>
public class MusicPlayer : MonoBehaviour
{
    const int gameSceneIndex = 1;

    [SerializeField] float volume = 0.22f;
    [SerializeField] float fadeSeconds = 1.4f;

    AudioSource a;
    AudioSource b;
    AudioSource live;

    AudioClip menu;
    AudioClip lobby;
    AudioClip warmup;
    AudioClip combat;
    AudioClip over;
    AudioClip wanted;

    /// <summary>
    /// Which track belongs to where we are.
    ///
    /// Five moments, because they're genuinely different: sitting on the title screen, waiting
    /// in a room with people, the seconds before it goes live, the match, and the scoreboard.
    /// All of it falls out of state that already exists - the scene, whether we're in a room,
    /// and the match phase - so none of it needs wiring up anywhere.
    ///
    /// Every slot falls back rather than going silent, so a partial set still works: no lobby
    /// track and the menu one carries on, no warmup and combat starts early. One file in the
    /// folder still plays everywhere.
    /// </summary>
    AudioClip should
    {
        get
        {
            bool inGame = SceneManager.GetActiveScene().buildIndex == gameSceneIndex;

            if (!inGame)
                return PhotonNetwork.InRoom ? Pick(lobby, menu) : Pick(menu, lobby);

            switch (MatchState.Phase)
            {
                case MatchPhase.Warmup: return Pick(warmup, combat, menu);
                case MatchPhase.Over:   return Pick(over, lobby, menu);
                default:                return Pick(combat, menu);
            }
        }
    }

    /// First one that exists, or the first thing loaded at all.
    AudioClip Pick(params AudioClip[] options)
    {
        foreach (AudioClip clip in options)
        {
            if (clip != null)
                return clip;
        }

        return menu ?? lobby ?? combat ?? warmup ?? over;
    }

    void Awake()
    {
        menu = Resources.Load<AudioClip>("Audio/Music/menu");
        lobby = Resources.Load<AudioClip>("Audio/Music/lobby");
        warmup = Resources.Load<AudioClip>("Audio/Music/warmup");
        combat = Resources.Load<AudioClip>("Audio/Music/combat");
        over = Resources.Load<AudioClip>("Audio/Music/over");

        if (menu == null && lobby == null && warmup == null && combat == null && over == null)
        {
            enabled = false;
            return;
        }

        a = Build("~musicA");
        b = Build("~musicB");
        live = a;
    }

    AudioSource Build(string name)
    {
        GameObject host = new GameObject(name);
        host.transform.SetParent(transform, false);

        AudioSource source = host.AddComponent<AudioSource>();
        source.loop = true;   // the short ones repeat rather than leaving silence
        source.playOnAwake = false;
        source.spatialBlend = 0f;   // music is not in the world
        source.volume = 0f;
        source.priority = 200;      // never steals a voice from a gunshot

        return source;
    }

    void Update()
    {
        if (should != wanted)
            Swap(should);

        float step = Time.unscaledDeltaTime / Mathf.Max(fadeSeconds, 0.01f);

        // The live one comes up, the other goes down and stops once it's silent.
        // The serialized figure is the track's own level in the mix - some of these were
        // mastered louder than others - and the slider scales all of them together.
        // Ducked while the player is genuinely flying. Not while running - SpeedRush only
        // reports anything above a threshold well past ground speed, so crossing a room leaves
        // the music exactly where it was.
        float target = volume * GameSettings.MusicVolume * (1f - 0.45f * SpeedRush.Intensity);

        live.volume = Mathf.MoveTowards(live.volume, wanted != null ? target : 0f,
                                        step * Mathf.Max(0.01f, target));

        AudioSource other = live == a ? b : a;
        other.volume = Mathf.MoveTowards(other.volume, 0f,
                                         step * Mathf.Max(0.01f, volume * GameSettings.MusicVolume));

        if (other.volume <= 0.001f && other.isPlaying)
            other.Stop();
    }

    void Swap(AudioClip clip)
    {
        wanted = clip;

        if (clip == null)
            return;

        // Already playing on this source - nothing to do. Restarting it here is what made the
        // same track audible twice: the incoming source starts the clip from zero while the
        // outgoing one is still fading out the same music, so you hear it against itself,
        // slightly out of phase.
        if (live.clip == clip && live.isPlaying)
            return;

        AudioSource other = live == a ? b : a;

        // If the other source already has this track running, hand over to it rather than
        // starting a third copy.
        if (other.clip == clip && other.isPlaying)
        {
            live = other;
            return;
        }

        // Onto whichever source isn't currently carrying the track, so the outgoing one has
        // something to fade out from.
        live = other;

        live.clip = clip;
        live.volume = 0f;
        live.Play();
    }
}
