using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Plays the menu loop in the menu and the combat loop in a match, and crossfades between them.
///
/// Lives on RoomManager, which survives the trip between scenes - a music player that reloads
/// with the scene restarts the track every time you join a room, which is worse than no music.
/// Two sources rather than one so a change is a fade rather than a cut; everything else here
/// snaps on purpose, but music is the one thing where a hard cut sounds like a bug.
///
/// Does nothing at all if the clips aren't there. They're generated by tools/music_generator.py
/// and deleting them is the whole uninstall.
/// </summary>
public class MusicPlayer : MonoBehaviour
{
    const int gameSceneIndex = 1;

    [SerializeField] float volume = 0.22f;
    [SerializeField] float fadeSeconds = 1.4f;

    AudioSource a;
    AudioSource b;
    AudioSource live;

    AudioClip menu;
    AudioClip combat;
    AudioClip wanted;

    void Awake()
    {
        menu = Resources.Load<AudioClip>("Audio/Music/menu");
        combat = Resources.Load<AudioClip>("Audio/Music/combat");

        if (menu == null && combat == null)
        {
            enabled = false;
            return;
        }

        a = Build("~musicA");
        b = Build("~musicB");
        live = a;
    }

    AudioSource Build(string name)
    {
        GameObject host = new GameObject(name);
        host.transform.SetParent(transform, false);

        AudioSource source = host.AddComponent<AudioSource>();
        source.loop = true;
        source.playOnAwake = false;
        source.spatialBlend = 0f;   // music is not in the world
        source.volume = 0f;
        source.priority = 200;      // never steals a voice from a gunshot

        return source;
    }

    void Update()
    {
        AudioClip should = SceneManager.GetActiveScene().buildIndex == gameSceneIndex ? combat : menu;

        if (should != wanted)
            Swap(should);

        float step = Time.unscaledDeltaTime / Mathf.Max(fadeSeconds, 0.01f);

        // The live one comes up, the other goes down and stops once it's silent.
        live.volume = Mathf.MoveTowards(live.volume, wanted != null ? volume : 0f, step * volume);

        AudioSource other = live == a ? b : a;
        other.volume = Mathf.MoveTowards(other.volume, 0f, step * volume);

        if (other.volume <= 0.001f && other.isPlaying)
            other.Stop();
    }

    void Swap(AudioClip clip)
    {
        wanted = clip;

        if (clip == null)
            return;

        // Onto whichever source isn't currently carrying the track, so the outgoing one has
        // something to fade out from.
        live = live == a ? b : a;

        live.clip = clip;
        live.volume = 0f;
        live.Play();
    }
}
